const db = require("./db");
const { collection, addDoc } = require('firebase/firestore');

const menus = [
  { "name": "제육폭탄덮밥", "price": 8900, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "도시락제육덮밥", "price": 7500, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "치즈제육도시락", "price": 8900, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "치킨덮밥", "price": 7500, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "항정살덮밥", "price": 8500, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "삼겹살덮밥", "price": 7900, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "직화된장삼겹덮밥", "price": 8500, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "중화제육덮밥", "price": 7900, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "우삼겹덮밥", "price": 8900, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "소불고기덮밥", "price": 8500, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "마라삼겹덮밥", "price": 7900, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "간장계란덮밥", "price": 6000, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "대창덮밥", "price": 7900, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "낙곱새덮밥", "price": 7900, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "낙지덮밥", "price": 7900, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "연어장덮밥", "price": 8500, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "새우장덮밥", "price": 9900, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "데리치킨마요덮밥", "price": 5500, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "김치제육덮밥", "price": 5500, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "스팸마요덮밥", "price": 4900, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "참치마요덮밥", "price": 4900, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "소세지야채볶음밥", "price": 7000, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "연어새우계란듬뿍덮밥", "price": 9900, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "돌솥알밥", "price": 8000, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "갈비탕", "price": 7900, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "스팸순두부", "price": 7000, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "우삼겹순두부", "price": 7900, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "해물순두부", "price": 7000, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "마라순두부", "price": 7000, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "레전드고기폭탄순두부", "price": 8900, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "치즈순두부", "price": 7900, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "사골떡만두국", "price": 6500, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "부대찌개", "price": 7900, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "뚝배기불고기", "price": 8500, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "돼지김치비빔", "price": 8500, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "김치찌개", "price": 6500, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "김밥", "price": 3500, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "라면김밥세트", "price": 7500, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "라면공기밥", "price": 4500, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "물냉면", "price": 7000, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "비빔냉면", "price": 7000, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "세트(물냉면+삼겹살)", "price": 9500, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "세트(비빔냉면+삼겹살)", "price": 9500, "store": "공여사&덮다", "image": "https://via.placeholder.com/150" },
  { "name": "홍우동+완탕", "price": 9500, "store": "수오미엔", "image": "https://via.placeholder.com/150" },
  { "name": "홍우동+밀크티 세트", "price": 9000, "store": "수오미엔", "image": "https://via.placeholder.com/150" },
  { "name": "유니 짜장면", "price": 7000, "store": "수오미엔", "image": "https://via.placeholder.com/150" },
  { "name": "우육면+콜라/사이다 세트", "price": 9500, "store": "수오미엔", "image": "https://via.placeholder.com/150" },
  { "name": "우육면+밀크티", "price": 10000, "store": "수오미엔", "image": "https://via.placeholder.com/150" },
  { "name": "우육면+가지튀김 세트", "price": 12000, "store": "수오미엔", "image": "https://via.placeholder.com/150" },
  { "name": "우육면", "price": 8500, "store": "수오미엔", "image": "https://via.placeholder.com/150" },
  { "name": "대창면", "price": 7500, "store": "수오미엔", "image": "https://via.placeholder.com/150" },
  { "name": "완탕면", "price": 7500, "store": "수오미엔", "image": "https://via.placeholder.com/150" },
  { "name": "새우완탕", "price": 2000, "store": "수오미엔", "image": "https://via.placeholder.com/150" },
  { "name": "중화비빔면", "price": 7500, "store": "수오미엔", "image": "https://via.placeholder.com/150" },
  { "name": "마파두부", "price": 7000, "store": "수오미엔", "image": "https://via.placeholder.com/150" },
  { "name": "짜장덮밥", "price": 7000, "store": "수오미엔", "image": "https://via.placeholder.com/150" },
  { "name": "폴로덮밥", "price": 8000, "store": "수오미엔", "image": "https://via.placeholder.com/150" },
  { "name": "미니 폴로덮밥", "price": 6500, "store": "수오미엔", "image": "https://via.placeholder.com/150" },
  { "name": "가지튀김(소)", "price": 4900, "store": "수오미엔", "image": "https://via.placeholder.com/150" },
  { "name": "쌀국수세트", "price": 9900, "store": "홍대쌀국수", "image": "https://via.placeholder.com/150" },
  { "name": "볶음밥세트", "price": 11000, "store": "홍대쌀국수", "image": "https://via.placeholder.com/150" },
  { "name": "마라탕+밥(홍우동)", "price": 7500, "store": "홍대쌀국수", "image": "https://via.placeholder.com/150" },
  { "name": "토마토-감자탕 쌀국수", "price": 8900, "store": "홍대쌀국수", "image": "https://via.placeholder.com/150" },
  { "name": "온면", "price": 6500, "store": "홍대쌀국수", "image": "https://via.placeholder.com/150" },
  { "name": "홍대쌀국수", "price": 5500, "store": "홍대쌀국수", "image": "https://via.placeholder.com/150" },
  { "name": "소고기쌀국수", "price": 6500, "store": "홍대쌀국수", "image": "https://via.placeholder.com/150" },
  { "name": "닭고기쌀국수", "price": 6500, "store": "홍대쌀국수", "image": "https://via.placeholder.com/150" },
  { "name": "소고기볶음 쌀국수", "price": 7000, "store": "홍대쌀국수", "image": "https://via.placeholder.com/150" },
  { "name": "소고기폭탄쌀국수", "price": 8500, "store": "홍대쌀국수", "image": "https://via.placeholder.com/150" },
  { "name": "돼지불고기쌀국수", "price": 6500, "store": "홍대쌀국수", "image": "https://via.placeholder.com/150" },
  { "name": "얼큰한 내 영혼의 쌀국수", "price": 7500, "store": "홍대쌀국수", "image": "https://via.placeholder.com/150" },
  { "name": "소불고기 볶음면", "price": 7000, "store": "홍대쌀국수", "image": "https://via.placeholder.com/150" },
  { "name": "소불고기 볶음밥", "price": 7500, "store": "홍대쌀국수", "image": "https://via.placeholder.com/150" },
  { "name": "해물볶음밥", "price": 6500, "store": "홍대쌀국수", "image": "https://via.placeholder.com/150" },
  { "name": "돼지불고기 볶음밥", "price": 7500, "store": "홍대쌀국수", "image": "https://via.placeholder.com/150" },
  { "name": "새우볶음밥", "price": 7500, "store": "홍대쌀국수", "image": "https://via.placeholder.com/150" },
  { "name": "계란후라이볶음밥", "price": 7500, "store": "홍대쌀국수", "image": "https://via.placeholder.com/150" },
  { "name": "짜장면", "price": 4500, "store": "대한짜장", "image": "https://via.placeholder.com/150" },
  { "name": "간짜장", "price": 5500, "store": "대한짜장", "image": "https://via.placeholder.com/150" },
  { "name": "짬뽕", "price": 5500, "store": "대한짜장", "image": "https://via.placeholder.com/150" },
  { "name": "냉면", "price": 5000, "store": "대한짜장", "image": "https://via.placeholder.com/150" },
  { "name": "콩국수", "price": 5000, "store": "대한짜장", "image": "https://via.placeholder.com/150" },
  { "name": "물만두", "price": 5000, "store": "대한짜장", "image": "https://via.placeholder.com/150" },
  { "name": "군만두", "price": 5000, "store": "대한짜장", "image": "https://via.placeholder.com/150" },
  { "name": "볶음밥", "price": 6000, "store": "대한짜장", "image": "https://via.placeholder.com/150" },
  { "name": "잡채밥", "price": 7000, "store": "대한짜장", "image": "https://via.placeholder.com/150" },
  { "name": "삼선짬뽕", "price": 8000, "store": "대한짜장", "image": "https://via.placeholder.com/150" },
  { "name": "삼선짜장", "price": 8000, "store": "대한짜장", "image": "https://via.placeholder.com/150" },
  { "name": "굴짬뽕", "price": 8000, "store": "대한짜장", "image": "https://via.placeholder.com/150" },
  { "name": "유슬짜장", "price": 8000, "store": "대한짜장", "image": "https://via.placeholder.com/150" },
  { "name": "쟁반짜장", "price": 8000, "store": "대한짜장", "image": "https://via.placeholder.com/150" },
  { "name": "송이밥", "price": 8000, "store": "대한짜장", "image": "https://via.placeholder.com/150" },
  { "name": "삼선우동", "price": 8000, "store": "대한짜장", "image": "https://via.placeholder.com/150" },
  { "name": "중국냉면", "price": 8000, "store": "대한짜장", "image": "https://via.placeholder.com/150" },
  { "name": "연어초밥", "price": 18000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "새우초밥", "price": 18000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "모듬초밥", "price": 18000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "하즈벤 도시락", "price": 20000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "연어국수 세트", "price": 21000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "제주흑돼지 돈가스", "price": 12000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "한상정식", "price": 16000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "통모짜치즈돈가스 정식", "price": 15000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "가츠동", "price": 10000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "에비동", "price": 10000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "믹스동", "price": 11000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "사케동", "price": 16000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "카이센동", "price": 23000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "간장연어덮밥", "price": 16000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "연어덮밥", "price": 17000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "회덮밥", "price": 13000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "차슈동", "price": 13000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "치킨가라아게카레", "price": 12000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "감자고로케카레", "price": 12000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "돈가스카레", "price": 12000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "왕새우카레", "price": 12000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "냉모밀", "price": 9000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "냉모밀세트", "price": 14000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "판모밀", "price": 9000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "판모밀세트", "price": 14000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "가라아게카레우동", "price": 9500, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "우동", "price": 7000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "우동세트", "price": 12000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "탄탄멘", "price": 10000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "탄탄멘세트", "price": 15000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "돈코츠라멘", "price": 10000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "돈코츠라멘세트", "price": 15000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "감자고로케(5P)", "price": 8000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "치킨가라아게(8P)", "price": 9000, "store": "하즈벤", "image": "https://via.placeholder.com/150" },
  { "name": "전통 육개장", "price": 10000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "전통육개장 칼국수", "price": 10000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "차돌박이 육개장", "price": 12000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "부대 육개장", "price": 12000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "버섯 육개장", "price": 11000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "순두부 육개장", "price": 11000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "한방 삼계탕", "price": 14000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "들깨 삼계탕", "price": 14000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "맑은 육개장", "price": 10000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "사골떡 만두국", "price": 10000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "얼큰 닭칼국수", "price": 13000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "얼큰 닭개장", "price": 13000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "어린이 맑은육개장", "price": 7000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "어린이 사골떡만두국", "price": 7000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "맑은 닭개장", "price": 13000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "한우소머리 곰탕", "price": 12000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "모듬수육전골 (대)", "price": 35000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "모듬수육전골 (특)", "price": 45000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "설렁탕육수전골 (대)", "price": 30000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "설렁탕육수전골 (특)", "price": 45000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "부대 전골 (대)", "price": 30000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "부대 전골 (특)", "price": 45000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "곱창순대모듬 (대)", "price": 25000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "곱창순대모듬 (특)", "price": 35000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "사골차돌구이 (소)", "price": 14000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "사골차돌구이 (대)", "price": 28000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "야채곱창볶음 (소)", "price": 12000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "야채곱창볶음 (대)", "price": 24000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "전통보쌈 (대)", "price": 25000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "전통보쌈 (특)", "price": 45000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "족보세트", "price": 40000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "미니족발", "price": 25000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "왕만두전골", "price": 14000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "돈까스", "price": 8000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "석쇠불고기", "price": 15000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "찐만두", "price": 8000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "냉면", "price": 8000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "메밀전병", "price": 8000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "한입김치메밀전병+수수부꾸미", "price": 8000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "갈비만두", "price": 4000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "궁중만두(고기/김치)", "price": 7000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "육개장 세트", "price": 32000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "육+차 세트", "price": 34000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "차돌 세트", "price": 36000, "store": "또바기육개장", "image": "https://via.placeholder.com/150" },
  { "name": "뼈해장국", "price": 10000, "store": "엄가네해장국", "image": "https://via.placeholder.com/150" },
  { "name": "뼈우거지해장국", "price": 10000, "store": "엄가네해장국", "image": "https://via.placeholder.com/150" },
  { "name": "특(곱빼기)", "price": 12000, "store": "엄가네해장국", "image": "https://via.placeholder.com/150" },
  { "name": "우거지해장국", "price": 9000, "store": "엄가네해장국", "image": "https://via.placeholder.com/150" },
  { "name": "내장탕", "price": 12000, "store": "엄가네해장국", "image": "https://via.placeholder.com/150" },
  { "name": "갈비탕", "price": 15000, "store": "엄가네해장국", "image": "https://via.placeholder.com/150" },
  { "name": "병천순대국밥", "price": 10000, "store": "엄가네해장국", "image": "https://via.placeholder.com/150" },
  { "name": "아리랑 핫도그", "price": 1000, "store": "아리랑핫도그", "image": "https://via.placeholder.com/150" },
  { "name": "감자 핫도그", "price": 1500, "store": "아리랑핫도그", "image": "https://via.placeholder.com/150" },
  { "name": "더킹 핫도그", "price": 1500, "store": "아리랑핫도그", "image": "https://via.placeholder.com/150" },
  { "name": "요거다 핫도그", "price": 3500, "store": "아리랑핫도그", "image": "https://via.placeholder.com/150" },
  { "name": "모짜렐라치즈 핫도그", "price": 1500, "store": "아리랑핫도그", "image": "https://via.placeholder.com/150" },
  { "name": "체다치즈 핫도그", "price": 1500, "store": "아리랑핫도그", "image": "https://via.placeholder.com/150" },
  { "name": "오징어먹물 핫도그", "price": 1500, "store": "아리랑핫도그", "image": "https://via.placeholder.com/150" },
  { "name": "치즈 핫도그", "price": 3500, "store": "아리랑핫도그", "image": "https://via.placeholder.com/150" },
  { "name": "감자렐라 핫도그", "price": 2000, "store": "아리랑핫도그", "image": "https://via.placeholder.com/150" },
  { "name": "체다렐라 핫도그", "price": 2000, "store": "아리랑핫도그", "image": "https://via.placeholder.com/150" },
  { "name": "롱소세지 핫도그", "price": 3500, "store": "아리랑핫도그", "image": "https://via.placeholder.com/150" },
  { "name": "로얄쇼콜라라떼", "price": 3500, "store": "아리랑핫도그", "image": "https://via.placeholder.com/150" },
  { "name": "초코/녹차라떼", "price": 3000, "store": "아리랑핫도그", "image": "https://via.placeholder.com/150" },
  { "name": "레몬자몽TEA", "price": 3000, "store": "아리랑핫도그", "image": "https://via.placeholder.com/150" },
  { "name": "아메리카노", "price": 1500, "store": "아리랑핫도그", "image": "https://via.placeholder.com/150" },
  { "name": "카페라떼", "price": 2000, "store": "아리랑핫도그", "image": "https://via.placeholder.com/150" },
  { "name": "바닐라라떼", "price": 2500, "store": "아리랑핫도그", "image": "https://via.placeholder.com/150" },
  { "name": "구름스무디", "price": 4000, "store": "아리랑핫도그", "image": "https://via.placeholder.com/150" },
  { "name": "딸기/플레인 요거트", "price": 3500, "store": "아리랑핫도그", "image": "https://via.placeholder.com/150" },
  { "name": "녹차/쿠앤크 프라푸치노", "price": 3800, "store": "아리랑핫도그", "image": "https://via.placeholder.com/150" },
  { "name": "레몬/자몽 에이드", "price": 3000, "store": "아리랑핫도그", "image": "https://via.placeholder.com/150" },
  { "name": "콜라", "price": 1000, "store": "아리랑핫도그", "image": "https://via.placeholder.com/150" },
  { "name": "사이다", "price": 1000, "store": "아리랑핫도그", "image": "https://via.placeholder.com/150" },
  { "name": "환타 오렌지", "price": 1000, "store": "아리랑핫도그", "image": "https://via.placeholder.com/150" },
  { "name": "환타 파인", "price": 1000, "store": "아리랑핫도그", "image": "https://via.placeholder.com/150" },
  { "name": "크앙-라떡", "price": 5500, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "플떡볶이", "price": 6500, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "크앙 고기-라떡", "price": 9000, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "로제크림파스타볶이", "price": 8900, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "크뒹김말이튀김 (베이컨+치즈)", "price": 3900, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "순대꼬치튀김(2EA)", "price": 2500, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "못난이칠순대", "price": 5000, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "소떡소떡", "price": 3500, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "순살치킨가라아게(5EA)", "price": 4900, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "튀김범벅", "price": 8900, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "기본튀김", "price": 8900, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "꼬불이오뎅", "price": 1500, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "심쿵(삼겹살+쫄면)", "price": 8900, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "크쫄떡볶이", "price": 6500, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "대왕 수제 김말이", "price": 3900, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "순살치킨가라아게(5EA)", "price": 4900, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "뿌링클 치즈볼", "price": 4900, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "직화안창살스테이크미니덮밥", "price": 7500, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "우삼겹 미니덮밥", "price": 5900, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "치킨 마요 미니덮밥", "price": 5900, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "스팸마요 미니덮밥", "price": 5900, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "참치마요 미니덮밥", "price": 5900, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "떡갈비 미니덮밥", "price": 6500, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "직화삼겹살/불삼겹살 미니덮밥", "price": 6500, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "치킨 카레덮밥", "price": 7500, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "돈까스카레덮밥", "price": 7500, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "떡갈비 카레덮밥", "price": 7500, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "새우 카레덮밥", "price": 8500, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "SET1 실물세트", "price": 16700, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "SET2 헤비작세트", "price": 20600, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "SET3 시그니처세트", "price": 21200, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "SET4 배불배불세트", "price": 27700, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "크앙순대볶음", "price": 8500, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "치즈버터먹태구이", "price": 8500, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "음료수", "price": 2000, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "뽀로로음료수", "price": 1500, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "생수", "price": 1000, "store": "크앙분식", "image": "https://via.placeholder.com/150" },
  { "name": "라면 (단품)", "price": 1900, "store": "라면집", "image": "https://via.placeholder.com/150" },
  { "name": "라면세트 (계란, 치즈, 주먹밥 중 1가지 추가시)", "price": 2500, "store": "라면집", "image": "https://via.placeholder.com/150" },
  { "name": "오늘의 라면", "price": 3500, "store": "라면집", "image": "https://via.placeholder.com/150" },
  { "name": "프리미엄라면", "price": 4000, "store": "라면집", "image": "https://via.placeholder.com/150" },
  { "name": "덮밥류", "price": 4500, "store": "라면집", "image": "https://via.placeholder.com/150" },
  { "name": "황제라면 세트 (라면 + 덮밥)", "price": 5900, "store": "라면집", "image": "https://via.placeholder.com/150" }
]

async function addMenus() {
  const menusCollection = collection(db, "menus");

  for (const menu of menus) {
    try {
      await addDoc(menusCollection, menu);
      console.log(`✅ 메뉴 추가 완료: ${menu.name}`);
    } catch (error) {
      console.error(`❌ 메뉴 추가 실패: ${menu.name}`, error);
    }
  }

  console.log("🍚 모든 메뉴 추가 완료!");
}

addMenus();